apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-proxy-service
  labels:
    component: elasticsearch
    role: proxy
spec:
  selector:
    component: elasticsearch
    role: proxy
  ports:
  - name: http
    port: 9200
#type: LoadBalancer
